---
# This playbook attempts to install Tacker

- name: install tacker on target server 
  hosts: tacker-server
  remote_user: root

  roles:
    - server-install

- name: install tacker database
  hosts: database
  remote_user: stack

  roles:
    -  database-install

- name: install horizon plugin on controllers
  hosts: controller
  remote_user: stack

  roles:
    - horizon-install

- name: configure tacker server
  hosts: tacker-server
  remote_user: root

  roles:
    - server-configure

- name: configure tacker database
  hosts: database
  remote_user: stack

  roles:
    - database-configure

- name: start tacker server
  hosts: tacker-server
  remote_user: root

  roles:
    - server-start
