---
- name: create tacker.conf
  template: src=tacker.conf.j2 dest=/etc/tacker/tacker.conf

- name: configure Tacker database
  command: /usr/bin/tacker-db-manage --config-file /etc/tacker/tacker.conf upgrade head
