---
- name: add rhos-release latest repos
  shell: >
    rpm -ivh http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm && rhos-release -p GA 8-director && rhos-release -p GA 8
  register: add_rhos_release_repos
  failed_when: add_rhos_release_repos.stderr != '' and 'is already installed' not in add_rhos_release_repos.stderr

- name: download epel 7 repo
  get_url: url=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm dest=/root/epel-release-latest-7.noarch.rpm

- name: add epel 7 repo
  yum: name=/root/epel-release-latest-7.noarch.rpm state=installed
