---
- name: install git and pip
  yum: name={{ item }} state=present
  with_items:
   - git
   - python-pip

- name: ensure Neutron uses port_security extension driver
  lineinfile: dest=/etc/neutron/plugins/ml2/ml2_conf.ini regexp=^extension_drivers\s*= line='extension_drivers = port_security'
  register: neutron_conf

- name: restart Neutron server
  command: pcs resource restart neutron-server
  when: neutron_conf.changed

- name: ensure Heat policy stuff
  lineinfile: dest=/etc/heat/policy.json regexp=^\"resource_types:OS::Nova::Flavor\":\s*\" line='"resource_types:OS::Nova::Flavor": "role:admin"'
  register: heat_policy

- name: restart Heat engine
  command: pcs resource restart heat-engine
  when: heat_policy.changed
